import os

excel = (
    "import { NextRequest, NextResponse } from 'next/server'\n"
    "import ExcelJS from 'exceljs'\n"
    "\n"
    "/* eslint-disable @typescript-eslint/no-explicit-any */\n"
    "\n"
    "type WalletSummary = { name: string; income: number; expense: number }\n"
    "type PeriodSummary = { label: string; income: number; expense: number }\n"
    "\n"
    "const HARI   = ['Minggu','Senin','Selasa','Rabu','Kamis','Jumat','Sabtu']\n"
    "const NAVY   = 'FF0F1E36'\n"
    "const GOLD   = 'FFC9973A'\n"
    "const GREEN  = 'FF059669'\n"
    "const RED    = 'FFDC2626'\n"
    "const WHITE  = 'FFFFFFFF'\n"
    "const LIGHT  = 'FFF9F6EF'\n"
    "const LIGHT2 = 'FFFEF7EC'\n"
    "\n"
    "function borders(): ExcelJS.Borders {\n"
    "  const s: ExcelJS.BorderStyle = 'thin'\n"
    "  return {\n"
    "    top:    { style: s, color: { argb: 'FFE5E7EB' } },\n"
    "    bottom: { style: s, color: { argb: 'FFE5E7EB' } },\n"
    "    left:   { style: s, color: { argb: 'FFE5E7EB' } },\n"
    "    right:  { style: s, color: { argb: 'FFE5E7EB' } },\n"
    "  }\n"
    "}\n"
    "\n"
    "function styleHeader(cell: ExcelJS.Cell, bg = NAVY) {\n"
    "  cell.font      = { bold: true, color: { argb: WHITE }, size: 10 }\n"
    "  cell.fill      = { type: 'pattern', pattern: 'solid', fgColor: { argb: bg } }\n"
    "  cell.alignment = { horizontal: 'center', vertical: 'middle' }\n"
    "  cell.border    = borders()\n"
    "}\n"
    "\n"
    "function rupiahCell(cell: ExcelJS.Cell, value: number, color?: string) {\n"
    "  cell.value     = value\n"
    '  cell.numFmt    = \'\"Rp\" #,##0\'\n'
    "  cell.alignment = { horizontal: 'right', vertical: 'middle' }\n"
    "  cell.border    = borders()\n"
    "  if (color) cell.font = { bold: true, color: { argb: color } }\n"
    "}\n"
    "\n"
    "function makeTitleRow(sh: ExcelJS.Worksheet, text: string, cols: number) {\n"
    "  sh.mergeCells('A1:' + String.fromCharCode(64 + cols) + '1')\n"
    "  const c   = sh.getCell('A1')\n"
    "  c.value   = text\n"
    "  c.font    = { bold: true, size: 13, color: { argb: NAVY } }\n"
    "  c.alignment = { horizontal: 'left', vertical: 'middle' }\n"
    "  sh.getRow(1).height = 26\n"
    "}\n"
)

with open(r'c:\Users\MSI\jurnalyst\app\api\reports\excel\route.ts', 'w', encoding='utf-8', newline='\n') as f:
    f.write(excel)
print('partial OK')